### ISSUE TITLE
Enable EFS as storage engine for buffer

### ISSUE THREAD

**Issue by szpuni** [SumoLogic/sumologic-kubernetes-collection#1388]
**Is your feature request related to a problem? Please describe.**
I have recently bumped into problem where I cannot use EBS volumes and solution to this problem was to use EFS as storage engine. Unfortunately this is not possible with current helm chart since EFS requires folders which needs to be created inside it and assign rights to it by ROOT user. There are few small challenges in that design because efs-cni driver doesn't have dynamic provisioning functionality as of yet so you would need to pre create Persistent Volumes.

**Describe the solution you'd like**
Solution to this problem is to use new Storage Class which allows connection to EFS. Next you would need to create new Persistent Volumes inside your kubernetes cluster. Since Fluentd uses Stateful set we would manually need to create Persistent Volumes with matching number of pods used by Fluentd. By default we have 3 so you would need to create 3 PV's with 10GB size declared.

Next part is to inject initContainer which basically runs as ROOT user and only thing it's allowed to do is to create folder if it doesn't exist and then change permissions to it so we have match with fsgroup settings.

I have already updated code in my fork which basically does that in Helm Chart.

https://github.com/szpuni/sumologic-kubernetes-collection/commit/1430b4065c2c8ceea26de411e48c75f0aca26b63

I do not want to create PR as of yet since this design still have issue. Even tho initContainer works well and all pods start as normal, we still cannot write to volume. I see that folder structure is created by sumologic code but it's unable to read, write files:

```
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:236:in `mkdir'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:236:in `fu_mkdir'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:200:in `each'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/buf_file.rb:122:in `start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/plugin/output.rb:438:in `start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-sumologic_output-1.7.1/lib/fluent/plugin/out_sumologic.rb:224:in `start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:200:in `block in start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:188:in `each'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:175:in `each'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:175:in `lifecycle'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:199:in `start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/engine.rb:248:in `start'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/engine.rb:147:in `run'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:693:in `block in run_worker'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:943:in `main_process'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:684:in `run_worker'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `load'
  2021-01-26 11:25:23 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `<main>'
2021-01-26 11:25:23 +0000 [error]: #0 unexpected error error_class=Errno::EACCES error="Permission denied @ dir_s_mkdir - /fluentd/buffer/logs.default"

kubectl exec sumologic-sumologic-fluentd-logs-0 -- bash
fluent@sumologic-sumologic-fluentd-logs-0:/$ ls -lna
total 0
drwxr-xr-x   1   0   0  43 Jan 26 11:25 .
drwxr-xr-x   1   0   0  43 Jan 26 11:25 ..
-rwxr-xr-x   1   0   0   0 Jan 26 11:25 .dockerenv
drwxr-xr-x   1   0   0  27 Jan 14 08:48 bin
drwxr-xr-x   2   0   0   6 Nov 22 12:37 boot
drwxr-xr-x   5   0   0 360 Jan 26 11:25 dev
drwxr-xr-x   1   0   0  66 Jan 26 11:25 etc
drwxr-xr-x   1 999 999  20 Jan 26 11:25 fluentd
drwxr-xr-x   2   0   0   6 Nov 22 12:37 home
drwxr-xr-x   1   0   0  30 Jan  6 13:06 lib
drwxr-xr-x   2   0   0  34 Dec  9 23:22 lib64
drwxr-xr-x   2   0   0   6 Dec  9 23:22 media
drwxr-xr-x   2   0   0   6 Dec  9 23:22 mnt
drwxr-xr-x   2   0   0   6 Dec  9 23:22 opt
dr-xr-xr-x 154   0   0   0 Jan 26 11:25 proc
drwx------   1   0   0  36 Jan  6 13:05 root
drwxr-xr-x   1   0   0  21 Jan 26 11:25 run
drwxr-xr-x   1   0   0  20 Dec 11 15:47 sbin
drwxr-xr-x   2   0   0   6 Dec  9 23:22 srv
dr-xr-xr-x  13   0   0   0 Jan 21 13:13 sys
drwxrwxrwt   1   0   0  63 Jan 26 11:25 tmp
drwxr-xr-x   1   0   0  19 Dec  9 23:22 usr
drwxr-xr-x   1   0   0  41 Dec  9 23:22 var
fluent@sumologic-sumologic-fluentd-logs-0:/$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
fluent       1     0  0 11:25 ?        00:00:00 tini -- /bin/entrypoint.sh fluentd
fluent       6     1  2 11:25 ?        00:00:01 /usr/local/bin/ruby /usr/local/bundle/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
fluent     106     0  0 11:25 pts/0    00:00:00 bash
fluent     171     6 79 11:26 ?        00:00:00 /usr/local/bin/ruby -Eascii-8bit:ascii-8bit /usr/local/bundle/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervisor
fluent     172   106  0 11:26 pts/0    00:00:00 ps -ef

fluent@sumologic-sumologic-fluentd-logs-0:/$ ls -al /fluentd/
total 12
drwxr-xr-x 1 fluent fluent   35 Jan 26 11:45 .
drwxr-xr-x 1 root   root     43 Jan 26 11:44 ..
drwxr-xr-x 4 root   root   6144 Jan 26 10:27 buffer
drwxrwsrwx 3 root   fluent 4096 Jan 26 11:25 etc
drwxr-xr-x 2 fluent fluent    6 Jan  6 13:06 log
drwxr-xr-x 2 fluent fluent    6 Jan  6 13:06 plugins
-rw-r--r-- 1 fluent fluent   12 Jan 26 11:45 testubg
```

Looks like problem here is with buffer folder which is created with ROOT access privileges and application is not able to reach it. 

Just note that /fluentd directory is created by init container and rights to it allow access but application somehow creates buffer directory and gives ownership to ROOT.

**Describe alternatives you've considered**
I do not yet see alternative

**Additional context**
This issue is linked to another issue which I'm trying to resolve https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1333

**Comment by sumo-drosiek** [comment]
Dynamic provisioning is now supported for EFS storages: https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/
