### ISSUE TITLE
otelgateway in constant CrashLoopBackOff when traces are enabled

### ISSUE THREAD

**Issue by pmbeaumier** [SumoLogic/sumologic-kubernetes-collection#2531]
**Describe the bug**
When enabling traces, the otelgateway keeps crashlooping. This issue has been seen in all chart versions starting `2.10.0`. Using chart version `2.9.1` works fine and traces show up in SumoLogic.

**Logs**
`otelgateway` logs deployed using chart version `2.17.0`
```
$ k logs sumologic-sumologic-otelgateway-65b9fd67c6-mnj4h
2022-09-15T15:38:22.741Z	info	memorylimiterprocessor/memorylimiter.go:145	Using percentage memory limiter	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "total_memory_mib": 2048, "limit_percentage": 75, "spike_limit_percentage": 20}
2022-09-15T15:38:22.741Z	info	memorylimiterprocessor/memorylimiter.go:113	Memory limiter configured	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces", "limit_mib": 1536, "spike_limit_mib": 409, "check_interval": 5}
2022-09-15T15:38:22.742Z	info	service/telemetry.go:107	Setting up own telemetry...
2022-09-15T15:38:22.743Z	info	service/telemetry.go:146	Serving Prometheus metrics	{"address": ":8888", "level": "basic"}
2022-09-15T15:38:22.743Z	info	extensions/extensions.go:42	Starting extensions...
2022-09-15T15:38:22.743Z	info	extensions/extensions.go:45	Extension is starting...	{"kind": "extension", "name": "memory_ballast"}
2022-09-15T15:38:22.748Z	info	ballastextension/memory_ballast.go:52	Setting memory ballast	{"MiBs": 250}
2022-09-15T15:38:22.748Z	info	extensions/extensions.go:49	Extension started.	{"kind": "extension", "name": "memory_ballast"}
2022-09-15T15:38:22.748Z	info	extensions/extensions.go:45	Extension is starting...	{"kind": "extension", "name": "pprof"}
2022-09-15T15:38:22.749Z	info	pprofextension@v0.54.0/pprofextension.go:71	Starting net/http/pprof server	{"config": {"TCPAddr":{"Endpoint":"localhost:1777"},"BlockProfileFraction":0,"MutexProfileFraction":0,"SaveToFile":""}}
2022-09-15T15:38:22.749Z	info	extensions/extensions.go:49	Extension started.	{"kind": "extension", "name": "pprof"}
2022-09-15T15:38:22.749Z	info	extensions/extensions.go:45	Extension is starting...	{"kind": "extension", "name": "health_check"}
2022-09-15T15:38:22.749Z	info	healthcheckextension@v0.54.0/healthcheckextension.go:44	Starting health_check extension	{"config": {"Port":0,"TCPAddr":{"Endpoint":"0.0.0.0:13133"},"Path":"/","CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2022-09-15T15:38:22.749Z	info	extensions/extensions.go:49	Extension started.	{"kind": "extension", "name": "health_check"}
2022-09-15T15:38:22.749Z	info	pipelines/pipelines.go:74	Starting exporters...
2022-09-15T15:38:22.749Z	info	pipelines/pipelines.go:78	Exporter is starting...	{"kind": "exporter", "data_type": "traces", "name": "loadbalancing"}
2022-09-15T15:38:22.757Z	warn	loadbalancingexporter@v0.54.0/resolver_dns.go:80	failed to resolve	{"kind": "exporter", "data_type": "traces", "name": "loadbalancing", "resolver": "dns", "error": "lookup sumologic-sumologic-otelcol-headless.kube-system on 172.20.0.10:53: no such host"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:82	Exporter started.	{"kind": "exporter", "data_type": "traces", "name": "loadbalancing"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:78	Exporter is starting...	{"kind": "exporter", "data_type": "metrics", "name": "otlp"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:82	Exporter started.	{"kind": "exporter", "data_type": "metrics", "name": "otlp"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:86	Starting processors...
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:90	Processor is starting...	{"kind": "processor", "name": "batch", "pipeline": "traces"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:94	Processor started.	{"kind": "processor", "name": "batch", "pipeline": "traces"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:90	Processor is starting...	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:94	Processor started.	{"kind": "processor", "name": "memory_limiter", "pipeline": "traces"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:90	Processor is starting...	{"kind": "processor", "name": "batch", "pipeline": "metrics"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:94	Processor started.	{"kind": "processor", "name": "batch", "pipeline": "metrics"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:90	Processor is starting...	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:94	Processor started.	{"kind": "processor", "name": "memory_limiter", "pipeline": "metrics"}
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:98	Starting receivers...
2022-09-15T15:38:22.757Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "jaeger", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	static/strategy_store.go:203	No sampling strategies provided or URL is unavailable, using defaults	{"kind": "receiver", "name": "jaeger", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "jaeger", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "opencensus", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "opencensus", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	otlpreceiver/otlp.go:70	Starting GRPC server on endpoint 0.0.0.0:4317	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	otlpreceiver/otlp.go:88	Starting HTTP server on endpoint 0.0.0.0:4318	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp/deprecated", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	otlpreceiver/otlp.go:88	Starting HTTP server on endpoint 0.0.0.0:55681	{"kind": "receiver", "name": "otlp/deprecated", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp/deprecated", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "zipkin", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "zipkin", "pipeline": "traces"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp", "pipeline": "metrics"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "metrics"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp/deprecated", "pipeline": "metrics"}
2022-09-15T15:38:22.758Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp/deprecated", "pipeline": "metrics"}
2022-09-15T15:38:22.758Z	info	healthcheck/handler.go:129	Health Check state change	{"status": "ready"}
2022-09-15T15:38:22.758Z	info	service/collector.go:220	Starting otelcol-sumo...	{"Version": "v0.54.0-sumo-0", "NumCPU": 8}
2022-09-15T15:38:22.758Z	info	service/collector.go:128	Everything is ready. Begin running and processing data.
2022-09-15T15:38:27.766Z	warn	loadbalancingexporter@v0.54.0/resolver_dns.go:106	failed to resolve	{"kind": "exporter", "data_type": "traces", "name": "loadbalancing", "resolver": "dns", "error": "lookup sumologic-sumologic-otelcol-headless.kube-system on 172.20.0.10:53: no such host"}
2022-09-15T15:38:32.764Z	warn	loadbalancingexporter@v0.54.0/resolver_dns.go:106	failed to resolve	{"kind": "exporter", "data_type": "traces", "name": "loadbalancing", "resolver": "dns", "error": "lookup sumologic-sumologic-otelcol-headless.kube-system on 172.20.0.10:53: no such host"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf33338]

goroutine 145 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*hashRing).findEndpoint(0xc0004aced0?, 0x6615a0?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.54.0/consistent_hashing.go:64 +0x18
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*hashRing).endpointFor(0x9c1a59ef17feed15?, {{{0xd7, 0x6, 0xfc, 0xf4, 0x7d, 0x68, 0x1, 0x67, 0xcf, ...}}})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.54.0/consistent_hashing.go:59 +0xb0
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*loadBalancerImp).Endpoint(0xc000836880?, {{{0xd7, 0x6, 0xfc, 0xf4, 0x7d, 0x68, 0x1, 0x67, 0xcf, ...}}})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.54.0/loadbalancer.go:181 +0x95
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*traceExporterImp).consumeTrace(0xc000b12210, {0x57c8e80, 0xc000b122d0}, {0x18?})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.54.0/trace_exporter.go:104 +0xb9
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*traceExporterImp).ConsumeTraces(0x0?, {0x57c8e80, 0xc000b122d0}, {0xc000157f80?})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.54.0/trace_exporter.go:92 +0x69
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export(0xc000b12270, {0x57c8e80, 0xc000b122d0}, 0x0?, 0x0)
	go.opentelemetry.io/collector@v0.54.0/processor/batchprocessor/batch_processor.go:262 +0x107
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems(0xc000344e70, 0xc000484e60)
	go.opentelemetry.io/collector@v0.54.0/processor/batchprocessor/batch_processor.go:176 +0x67
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle(0xc000344e70)
	go.opentelemetry.io/collector@v0.54.0/processor/batchprocessor/batch_processor.go:143 +0x17f
created by go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).Start
	go.opentelemetry.io/collector@v0.54.0/processor/batchprocessor/batch_processor.go:101 +0x6a
```

**Command used to install/upgrade Collection**
```
helm upgrade --install sumologic sumologic/sumologic \
  --namespace kube-system \
  --set sumologic.accessId=<REDACTED> \
  --set sumologic.accessKey=<REDACTED> \
  --set sumologic.clusterName="<REDACTED>" \
  --set sumologic.traces.enabled=true \
  --set sumologic.metrics.enabled=true \
  --set kube-prometheus-stack.enabled=true \
  --set falco.enabled=true \
  --atomic
```

**Configuration**
Helm values used to get removed metrics back:
```
kube-prometheus-stack:
  kubeApiServer:
    serviceMonitor:
      metricRelabelings: []
  kubelet:
    serviceMonitor:
      metricRelabelings: []
      cAdvisorMetricRelabelings: []
  kubeControllerManager:
    serviceMonitor:
      metricRelabelings: []
  coreDns:
    serviceMonitor:
      metricRelabelings: []
  kubeEtcd:
    serviceMonitor:
      metricRelabelings: []
  kubeScheduler:
    serviceMonitor:
      metricRelabelings: []
  kubeStateMetrics:
    serviceMonitor:
      metricRelabelings: []
  nodeExporter:
    serviceMonitor:
      metricRelabelings: []
```

**To Reproduce**
Deploy the sumologic integration version 2.10.0 or above with traces enabled

**Expected behavior**
The otelgateway gets in READY states and processes traces

**Environment (please complete the following information):**
 - **Collection version** (e.g. `helm ls -n sumologic`):
```
$ helm ls
sumologic                   	kube-system	8       	2022-09-15 15:31:42.759474388 +0000 UTC	deployed	sumologic-2.17.0                  	2.17.0
```
 - **Kubernetes version** (e.g. `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:52:41Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.12-eks-6d3986b", GitCommit:"dade57bbf0e318a6492808cf6e276ea3956aecbf", GitTreeState:"clean", BuildDate:"2022-07-20T22:06:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
 - **Cloud provider**:
AWS EKS `1.22.12-eks-6`

**Comment by pmbeaumier** [comment]
As it turns out, I had a misconfiguration in RBAC that was preventing autodiscovery to work. This was affecting the retrieval of the endpoints from the headless service and was leading to the CrashLoops.
