### ISSUE TITLE
otel-logs statefulset crash looping

### ISSUE THREAD

**Issue by poblahblahblah** [SumoLogic/sumologic-kubernetes-collection#2843]
**Describe the bug**
The otel-logs statefulset is crashlooping on one of our clusters

**Logs**
https://gist.github.com/poblahblahblah/d071cf34fc689f772bf206ab91b9beb9

**Command used to install/upgrade Collection**
ArgoCD installed via Helm

**Configuration**
https://gist.github.com/poblahblahblah/bb361d0f1b405656a83b74a0cfd62038

**To Reproduce**
It looks to be an issue with something a team is piloting - the [Strimzi Kubernetes Operator](https://strimzi.io/)

**Expected behavior**
We would exect the statefulset to be healthy

**Environment (please complete the following information):**
 - **Collection version**: 3.0.0
 - **Kubernetes version**: 1.23
 - **Cloud provider**: EKS
 - **Others**:

**Anything else do we need to know**
Only happening on clusters with the strimzi operator installed

**Comment by poblahblahblah** [comment]
Operator log (first ~150 lines): https://gist.github.com/poblahblahblah/20892167dd167f77a6daca4c5526fac7

**Comment by sumo-drosiek** [comment]
The issue is that the logs are processed line by line, so OpenTelemetry Collector is trying to parse `{` as json instead of 

```
{
  "instant" : {
    "epochSecond" : 1675125364,
    "nanoOfSecond" : 624915000
  },
  "thread" : "main",
  "level" : "INFO",
  "loggerName" : "io.strimzi.operator.cluster.Main",
  "message" : "ClusterOperator 0.32.0 is starting",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.spi.AbstractLogger",
  "threadId" : 1,
  "threadPriority" : 5
}
```

In order to work it as expected, I would recommend to [configure multiline](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/dcf26c56f5c19225b66b3645ee4c7e68217147b9/docs/collecting-container-logs.md#multiline-log-parsing) with the following regexp (to merge json into one log):

```
sumologic:
  logs:
    multiline:
      enabled: true
      first_line_regex: "(^\\[?\\d{4}-\\d{1,2}-\\d{1,2}.\\d{2}:\\d{2}:\\d{2}|^{$)"
```

**Comment by swiatekm-sumo** [comment]
> And unfortunately unsuccessful JSON parsing leads to crashloopbackoff

Now that sounds like a bug in logstransform processor. We can patch this with a better JSON regex a bit, but it really shouldn't be crashing. @sumo-drosiek have you tried reproducing this locally?

**Comment by sumo-drosiek** [comment]
Minimal reproduction:

`config.yaml`
```
exporters:
  logging:
    logLevel: debug
extensions:
  health_check: {}
  pprof: {}
receivers:
  filelog/containers:
    include:
    - ./gistfile1.txt
    start_at: beginning
service:
  extensions:
  - health_check
  - pprof
  pipelines:
    logs/containers:
      exporters:
      - logging
      processors:
        - logstransform/containers_parse_json
      receivers:
      - filelog/containers
  telemetry:
    logs:
      level: debug
processors:
  logstransform/containers_parse_json:
    operators:
    - if: body matches "^{.*"
      parse_from: body
      parse_to: body
      type: json_parser
```

`gistfile1.txt`
```
{
```

with internet connection:
```
2023-02-01T12:18:01.366+0100    error   helper/transformer.go:110       Failed to process entry {"kind": "processor", "name": "logstransform/containers_parse_json", "pipeline": "logs/containers", "operator_id": "json_parser", "operator_type": "json_parser", "error": "ReadString: expects \" or n, but found \u0000, error found in #1 byte of ...|{|..., bigger context ...|{|...", "action": "send", "entry": {"observed_timestamp":"2023-02-01T11:18:01.266325026Z","timestamp":"0001-01-01T00:00:00Z","body":"{","attributes":{"log.file.name":"gistfile1.txt"},"severity":0,"scope_name":""}}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/operator/helper/transformer.go:110
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/operator/helper/parser.go:151
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/operator/helper/parser.go:123
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/operator/helper/parser.go:109
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/json.(*Parser).Process
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/operator/parser/json/json.go:73
github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor.(*logsTransformProcessor).converterLoop
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor@v0.69.0/processor.go:154
2023-02-01T12:18:01.366+0100    error   logstransformprocessor@v0.69.0/processor.go:155 processor encountered an issue with the pipeline        {"kind": "processor", "name": "logstransform/containers_parse_json", "pipeline": "logs/containers", "error": "ReadString: expects \" or n, but found \u0000, error found in #1 byte of ...|{|..., bigger context ...|{|..."}
github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor.(*logsTransformProcessor).converterLoop
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor@v0.69.0/processor.go:155
2023-02-01T12:18:01.466+0100    info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
2023-02-01T12:18:02.266+0100    debug   fileconsumer/file.go:124        Consuming files {"kind": "receiver", "name": "filelog/containers", "pipeline": "logs", "component": "fileconsumer"}
2023-02-01T12:18:03.266+0100    debug   fileconsumer/file.go:124        Consuming files {"kind": "receiver", "name": "filelog/containers", "pipeline": "logs", "component": "fileconsumer"}
```

without internet connection :shrug: 
```
2023-02-01T12:19:41.259+0100    debug   pipeline/directed.go:89 Stopped operator        {"kind": "processor", "name": "logstransform/containers_parse_json", "pipeline": "logs/containers"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27e6494]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*Converter).Stop(0xc00099b6b0?)
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.69.0/adapter/converter.go:129 +0x14
github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor.(*logsTransformProcessor).Shutdown(0xc000a93560, {0x62c6c85?, 0x0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/logstransformprocessor@v0.69.0/processor.go:79 +0x65
go.opentelemetry.io/collector/service.(*builtPipelines).ShutdownAll(0xc0005f60a0, {0x6f44160, 0xc00007a0f0})
        go.opentelemetry.io/collector@v0.69.0/service/pipelines.go:131 +0x43a
go.opentelemetry.io/collector/service.(*Service).Shutdown(0xc00043c780, {0x6f44160, 0xc00007a0f0})
        go.opentelemetry.io/collector@v0.69.0/service/service.go:155 +0xd4
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc0016afaa8, {0x6f44160, 0xc00007a0f0})
        go.opentelemetry.io/collector@v0.69.0/otelcol/collector.go:181 +0x568
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0016afaa8, {0x6f44160, 0xc00007a0f0})
        go.opentelemetry.io/collector@v0.69.0/otelcol/collector.go:205 +0x65
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc0001be600, {0x626dcc2?, 0x2?, 0x2?})
        go.opentelemetry.io/collector@v0.69.0/otelcol/command.go:53 +0x419
github.com/spf13/cobra.(*Command).execute(0xc0001be600, {0xc000072190, 0x2, 0x2})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001be600)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.runInteractive({{0xc00147a180, 0xc00147b200, 0xc00147a4e0, 0xc001425e00}, {{0x6283f20, 0xc}, {0x6392345, 0x2f}, {0x629023d, 0xe}}, ...})
        github.com/SumoLogic/sumologic-otel-collector/main.go:37 +0x7d
main.run(...)
        github.com/SumoLogic/sumologic-otel-collector/main_others.go:11
main.main()
        github.com/SumoLogic/sumologic-otel-collector/main.go:25 +0x1d8
```

**Comment by poblahblahblah** [comment]
I'll give the multiline support a shot and see how it goes.

**Comment by poblahblahblah** [comment]
```
sumologic:
  logs:
    multiline:
      enabled: true
      first_line_regex: "(^\\[?\\d{4}-\\d{1,2}-\\d{1,2}.\\d{2}:\\d{2}:\\d{2}|^{$)"
```

This change appears to work.

Will the `first_line_regex` change be available in the next release, or is this something we should keep indefinitely?

**Comment by poblahblahblah** [comment]
Yeah - happy to help troubleshoot.

Can you set something up through our sumo rep?

**Comment by sumo-drosiek** [comment]
@poblahblahblah Could you try to reproduce the issue with the following configuration?

```
metadata:
  logs:
    logLevel: debug
otellogs:
  config:
    merge:
      receivers:
        filelog/containers:
          exclude:
            # do not scrape otelcol metadata logs
            - /var/log/pods/*otelcol-logs-*/*/*.log
```

I hope there will be some helpful debug logs just before the crash

**Comment by swiatekm-sumo** [comment]
Fix for the underlying issue: https://github.com/SumoLogic/sumologic-otel-collector/pull/938. It was an accident that the multiline configuration triggered this - it simply caused there to be more log lines and therefore more batches from the same Pod.

**Comment by poblahblahblah** [comment]
We're seeing this again on a different cluster, although I am unsure if it's the same issue.

pod logs: https://gist.github.com/poblahblahblah/a1cf2410a0d73410247caac967552b4b

This time it's an Azure AKS 1.21 cluster. I realize AKS 1.21 is not supported but AFAIK there's nothing about Kubernetes 1.21 that would be an issue.

**Comment by swiatekm-sumo** [comment]
@poblahblahblah can you try using the newly released [0.71.0-sumo-0](https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.71.0-sumo-0) version of otel?

```yaml
metadata:
  image:
    tag: 0.71.0-sumo-0
```

**Comment by poblahblahblah** [comment]
Setting metadata.image.tag to `0.71.0-sumo-0` looks good.

Will this be in the next release? If so, any idea on when that will be?

**Comment by swiatekm-sumo** [comment]
Should be in `3.1.1` which will happen early next week. CC @astencel-sumo

**Comment by poblahblahblah** [comment]
Did this make it in to 3.1.1?

**Comment by swiatekm-sumo** [comment]
> Did this make it in to 3.1.1?

It didn't, as we decided not to do this kind of change in a patch release. But it'll be in `3.2.0`, which should still happen this week.

**Comment by swiatekm-sumo** [comment]
@poblahblahblah the change was released in https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v3.2.0, once you upgrade to that version, you can undo the otel image config change.
